services:
  db:
      image: postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
      volumes:
        - kursovaya-db-data:/var/lib/postgresql/data
  # test_db:
  #     image: postgres
  #     restart: always
  #     ports:
  #       - "5432:5432"
  #     environment:
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: postgres
  #       POSTGRES_DB: postgres
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - kursovaya-pgadmin-data:/var/lib/pgadmin
  
volumes:
  kursovaya-db-data:
  kursovaya-pgadmin-data:
networks:
  kursovaya_network:
    driver: bridge